const breakfastItems = [
    'Idly,Sambar,Chutney',
    'Vada,Sambar,Chutney',
    'Pongal/KitchadiUpma',
    'Poori Masala',
    'Plain Dosa',
    'Uthappam',
    'Masala Dosa',
    'Podi Dosa',
    'Bread Toast',
    'Ghee Roast',
    'Masala Ghee Roast',
    'Rava Dosa, Podi Dosa',
    'Panneer Dosa /Mushroom Dosa', 
    'Double Egg Dosa', 
    'Baby Corn Dosa',
    'Chole Bhatura',
    'Aloo Paratha with Curd',
    'Corn Flakes with cold/hot milk',
    'Chocos with Cold/hot milk',
    'Corn Cheese Dosa',
    'Vada Paav',
    'Egg Dosa',
    'Chicken Kheema Dosa',
    'Chicken Cheese Dosa',
    'Chicken Curry Dosa',
    'Scrambled Egg',
    'Boiled Egg',
    'Banana Roti',
    'Bread Omelette',
    'Masala Omelette',
    'Cheese Omelette',
    'Egg Masala',
    'Fried Egg',
    'Spanish Omelette',
    'French Toast',
    'Egg Burji',
    'Full Boiled Egg',
    'Tea',
    'Ice Lemon Tea',
    'Green Tea',
    'Milk',
    'Coffee',
    'Ginger',
    'MasalaTea',
    'Apple',
    'Kiwi',
    'Avacado Juice',
    'Sweet lime',
    'Chickoo',
    'Guava',
    'Pineapple',
    'Grape',
    'Banana',
    'Lemon Juice',
    'Water Melon',
    'Mash Melon',
    'Lassi',
    'Cold Boost',
    'Cold Coffee',
    'Milk Shakes (AllFlavours)',
    'Pomagranut',
    'Mango',
    'Orange Juice',
    'Lemon',
    'Mint Juice',
    'Butter Milk',
    'Horlicks',
    'Boost',
  ];

  module.exports=breakfastItems;