const breakfastItems = [
    'Idly,Sambar,Chutney',
    'Vada,Sambar,Chutney',
    'Pongal/KitchadiUpma',
    'Poori Masala',
    'Plain Dosa/Uthappam',
    'Masala Dosa/ Uthappam/ Podi',
    'Bread Toast',
    'Ghee Roast',
    'Masala Ghee Roast',
    'Rava Dosa, Podi Dosa',
    'Chole Bhatura',
    'Aloo Paratha with Curd',
    'Corn Flakes with cold/hot milk',
    'Chocos with Cold/hot milk',
    'Corn Cheese Dosa',
    'Vada Paav',
    'Egg Dosa',
    'Chicken Kheema Dosa',
    'Chicken Cheese Dosa',
    'Chicken Curry Dosa',
    'Scrambled Egg',
    'Boiled Egg',
    'Banana Roti',
    'Bread Omelette',
    'Masala Omelette',
    'Cheese Omelette',
    'Egg Masala',
    'Fried Egg',
    'Spanish Omelette',
    'French Toast',
    'Egg Burji',
    'Full Boiled Egg',
  ];

  module.exports=breakfastItems;