const lunchdinnerItems=[
    'Plain Naan/Kulcha/Roti',
    'Butter Naan/Kulcha/Roti',
    'Garlic roti, Stuffed Roti',
    'Phulka',
    'Phulka Butter',
    'Chapathi/Paratha + Curry',
    'Plain Rice',
    'Veg Fried Rice/Noodles',
    'Paneer Fried Rice/Noodles',
    'Szechwan Veg Noodles/Rice',
    'Mushroom Fried Rice/Noodles',
    'Gobi 65 /Aloo 65',
    'Paneer 65/Mushroom 65',
    'Veg Manchurian',
    'Gobi Manchurian/ Paneer Tikka',
    'Baby corn Masala/Manchurian',
    'Paneer Manchurian',
    'Chilly Gobi/Aloo Chilly',
    'American Chopsy Veg',
    'Veg Meals with curd',
    'Curd',
    'Veg Biryani/Spl. Fried Rice',
    'Paneer plater',
    'Kadai Veg',
    'Paneer Chat pata',
    'Paneer Butter Masala',
    'Palak Paneer',
    'Paneer Peas Masala',
    'Green Peas Masala',
    'Mixed Veg Curry',
    'Gobi Masala',
    'Aloo Gobì Masala',
    'Aloo Capsicum Masala',
    'Aloo Muttar/Aloo jeera',
    'Dhal Fry',
    'Dhal Masala', 
    'Thadka',
    'Samosa Channa Chat',
    'Kachori Chat',
    'Bread Channa Chat',
    'Baby Corn 65',
    'Egg Fried Rice/Noodles',
    'Chicken Fried Rice/Noodles',
    'Szechwan Chicken Fried Rice',
    'Szechwan Chicken Noodles',
    'Chicken 65/Chicken Tikka',
    'Chicken Masala /Curry',
    'Malai Chicken /Mughlal',
    'Chicken Saagwala',
    'Chicken Hydrabadi/gravy',
    'Hariyali Chicken/Nilagiri',
    'Reshmy/Harabara Kebab',
    'Chicken Biryani with Egg',
    'Malabar Chicken Biriyani',
    'Hyderabadi Chicken Biriyani',
    'Mugalai Chicken Biriyani',
    'Ambur Chicken Biriyani',
    'Egg Biryani',
    'Mutton Biryani with Egg',
    'Nattu kozhi Biryani + Egg',
    'Chicken roganjosh',
    'Chicken Kholapuri',
    'Chicken Tikka masala',
    'Chicken Tikka Lababdar',
    'Malai Chicken Tikka Masala',
    'Chicken Chetinad',
    'Chicken Karakozhambu',
    'Chicken Do Plazha',
    'Chicken Makhani',
    'Chicken Sukka',
    'Bindi Masala/Bindi do piazha',
    'Veg do piazha/Hydrabadi',
    'Malai Koftha Curry',
    'Bindi Jaipuri/65',
    'Channa Masala Butter',
    'Panneer Fingers',
    'Chicken Loly pop',
    'Lollypop saucy',
    'Chicken Steak',
    'Dragon Chicken, 555 Chicken',
    'Malabar Chicken Masala', 
    'Chicken Punjabi /Spi.Chicken', 
    'Chicken Chowmein', 
    'Bisibilla Bath', 
    'Bagala Bath', 
    'Prawn Manchurian', 
    'Fish Pepper Masala', 
    'Fish fry (2 slice)', 
    'Chally Fish/ Chilly Manchurian',
    'Veg, Clear, Noodle Soup', 
    'Tomato Soup, Chetinad soup', 
    'Chicken Soup', 
    'Papad ( Masala/ Roasted)',
    'Apple',
    'Kiwi',
    'Avacado Juice',
    'Sweet lime',
    'Chickoo',
    'Guava',
    'Pineapple',
    'Grape',
    'Banana',
    'Water Melon',
    'Mash Melon',
    'Lassi',
    'Cold Boost',
    'Cold Coffee',
    'Milk Shakes (AllFlavours)',
    'Pomagranut',
    'Mango',
    'Orange Juice',
    'Lemon',
    'Mint Juice',
    'Butter Milk',
    'Horlicks',
    'Boost',
    'Gulab Jamun',
    'Rasmulal',
    'Rasgula',
    'Gova Mysore Paak',
    'Mothichoor Laddu',
    'Dry Jamun',
    'Dates Laddu',
    'Milk Sweet',
    'Special Sweet',
    'Redvelvet Pastry',
    'Muffins All flavours',
    'Special Pastries',
    'Vanilla,Strawberry Cakes',
    'Swiss Rolls,Jam Roll',
    'Queen of Pudding',
    'Eggless Cake',
    'Sponge Cake',
    'Plum Cake',
    'Pastries (All Flavours)',
    'Chocolate Cake',
    'Chocolate Croissants',
    'Doughnut Chocolate',
    'Doughnut Stuffed',
    'Brownie fudge',
    '7 C Jar',
    'Redvelvet Jar',
    'Brownie Sandwich',
    'Choco Lava',
    'Moose Cup',
    'Red Velvet Cup',
    'Apple Pie',
]

module.exports = lunchdinnerItems;