const snacksItems=[
    'Aloo Bonda',
    'Raw Banana Bajji',
    'Onion Pakoda',
    'Veg Samosa',
    'Onion Samosa',
    'Paav Bhaji',
    'Paav Bhaji with cheese',
    'Paav Bhaji Spl.',
    'Veg puffs',
    'Paneer puffs',
    'Veg Burger',
    'Veg & Cheese Burger',
    'Veg Sandwich Toasted',
    'Kachodi Fry, Samosa Fry',
    'Toasted Veg Club Sandwich',
    'French Fries',
    'Egg Puffs',
    'Chicken Puffs',
    'Chicken Rolls',
    'Chicken Francky',
    'Chicken Sandwich Toasted',
    'Hawain Chicken Sandwich',
    'Chicken Hot Dog',
    'Chicken Spring Rolls, Kothu Parota',
    'Omelete Sandwich',
    'Toasted Egg Sandwich',
    'Chicken Tikka Sandwich',
    'Chicken Burgert Cheese',
    'Grilled Chicken',
    'Tandoori Chicken',
    'Tangdi Kebab,ChickenTikka',
    'Maggie Noodies', 
    'Veg Pastha', 
    'Egg Pastha/ Panneer Pastha', 
    'Chicken Pastha',
    'Tea',
    'Ice Lemon Tea',
    'Green Tea',
    'Milk',
    'Coffee',
    'Ginger',
    'MasalaTea',
    'Apple',
    'Kiwi',
    'Avacado Juice',
    'Sweet lime',
    'Chickoo',
    'Guava',
    'Pineapple',
    'Grape',
    'Banana',
    'Water Melon',
    'Mash Melon',
    'Lassi',
    'Cold Boost',
    'Cold Coffee',
    'Coco / Chocolate Coffee',
    'Milk Shakes (AllFlavours)',
    'Pomagranut',
    'Mango',
    'Orange Juice',
    'Lemon',
    'Mint Juice',
    'Butter Milk',
    'Horlicks',
    'Boost',
    'Gulab Jamun',
    'Rasmulal',
    'Rasgula',
    'Gova Mysore Paak',
    'Mothichoor Laddu',
    'Dry Jamun',
    'Dates Laddu',
    'Milk Sweet',
    'Special Sweet',
    'Redvelvet Pastry',
    'Muffins All flavours',
    'Special Pastries',
    'Vanilla,Strawberry Cakes',
    'Swiss Rolls,Jam Roll',
    'Queen of Pudding',
    'Papdi Chat',
    'Pani Poori',
    'Channa Chat',
    'Dhai Papdi Chat',
    'Bhel Poori',
    'Dha Poori',
    'Dhai Vada',
    'Dhai Samosa',
    'Channa Masala',
    'Black Channa Masala',
    'Aloo Tikki',
    'Eggless Cake',
    'Sponge Cake',
    'Plum Cake',
    'Pastries (All Flavours)',
    'Chocolate Cake',
    'Chocolate Croissants',
    'Doughnut Chocolate',
    'Doughnut Stuffed',
    'Brownie fudge',
    '7 C Jar',
    'Redvelvet Jar',
    'Brownie Sandwich',
    'Choco Lava',
    'Moose Cup',
    'Red Velvet Cup',
    'Apple Pie',
]

module.exports=snacksItems;